name: CI

on:
  push:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format
        run: bun run format:check

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test

  storybook:
    runs-on: ubuntu-22.04
    env:
      VITE_RESAS_API_KEY: ${{ secrets.VITE_RESAS_API_KEY }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install playwright dependencies
        run: bun playwright install
      - name: Create .env file
        run: echo "VITE_RESAS_API_KEY=$VITE_RESAS_API_KEY" > .env
      - name: Run Storybook server
        run: bun run storybook &
      - name: Test Storybook
        run: bun run test-storybook
